spring:
  application:
    name: SecureHR

  datasource:
    driver-class-name: org.postgresql.Driver
    password: Nicole0509
    username: postgres
    url: jdbc:postgresql://localhost:5432/securehr

    jpa:
      properties:
        hibernate:
          format_sql: true
          show-sql: true
      hibernate:
        ddl-auto: update

server:
  port: 8081

app:
  jwt:
    key: Z2CUX889AL8BeQGjd08rej+H2qfEuLTJg4VvBfRogN8=Y/zX3ZRVCdoSsnmLgSte8t0hUs9ikuBE3+ZKWkuKopY=  #secret key
    expiration: 259200000ms #72 hours worth of token activation