spring:
  application:
    name: SecureHR

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}

  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${PROD_DB_PASSWORD}
    username: ${PROD_DB_USERNAME}
    url: ${PROD_DB_URL}


    jpa:
      properties:
        hibernate:
          format_sql: true
          show-sql: true
      hibernate:
        ddl-auto: update

server:
  port: 8081

app:
  jwt:
    key: ${JWT_SECRET}  #secret key
    expiration: ${JWT_EXPIRATION} #72 hours worth of token activation